// examples/shadow/src/assemblies/react-box/react-box.react.tsx
// Copyright Ayers Electronics Inc. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
import { useState } from "react";

export const shadow = true;

export default function ReactBox() {
  const [count, setCount] = useState(0);
  return (
    <button type="button" className="bump" id="react-bump" onClick={() => setCount(count + 1)}>
      react {count}
    </button>
  );
}

// examples/shadow/src/assemblies/solid-box/solid-box.solid.tsx
// Copyright Ayers Electronics Inc. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
import { createSignal } from "solid-js";

export const shadow = true;

export default function SolidBox() {
  const [count, setCount] = createSignal(0);
  return (
    <button type="button" class="bump" id="solid-bump" onClick={() => setCount(count() + 1)}>
      solid {count()}
    </button>
  );
}
