// packages/renderer-lit/src/client/slot.ts
// Copyright Ayers Electronics Inc. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
import { placementDirective } from "@assemblejs/core/client";
import { unsafeHTML } from "lit/directives/unsafe-html.js";

/**
 * Places a child assembly: writes the directive the composer replaces with the child's envelope,
 * for a view to put in its template as `${slot("cart")}`.
 *
 * The same directive on the server and in the browser, so the template Lit hydrates is the one
 * it rendered. This is the one thing a Lit view writes unescaped: the directive, built from a
 * name and a view.
 *
 * A Lit view may hold a Lit assembly, at any depth beneath it, only behind a shadow root: the
 * assembly's own, which `export const shadow = true` in its view gives it. Lit hydrates a view
 * by reading every marker in its tree, and one left in the same tree is refused when the view
 * mounts.
 */
export function slot(name: string, view?: string): ReturnType<typeof unsafeHTML> {
  return unsafeHTML(placementDirective(name, view));
}

// packages/renderer-solid/src/client/slot.ts
// Copyright Ayers Electronics Inc. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
import { placementDirective } from "@assemblejs/core/client";
import { createComponent } from "solid-js";
import type { JSX } from "solid-js";
import { Dynamic } from "solid-js/web";

/**
 * Places a child assembly: writes the directive the composer replaces with the child's envelope.
 *
 * It writes the same markup on the server and in the browser. On the server the composer puts
 * the child where the directive stood; in the browser Solid leaves what a slot holds alone,
 * while it hydrates and for as long as the directive it is given does not change.
 *
 * This is the one place a Solid assembly writes markup it did not escape, and what it writes is
 * only the directive, built from a name and a view. Nothing else in a Solid assembly may use
 * `innerHTML`.
 */
export function Slot(props: { readonly name: string; readonly view?: string }): JSX.Element {
  return createComponent(Dynamic, {
    component: "div",
    get "data-assembly-slot"() {
      return props.name;
    },
    get innerHTML() {
      return placementDirective(props.name, props.view);
    },
  });
}
