// packages/renderer-solid/src/client/hydrate.ts
// Copyright Ayers Electronics Inc. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
import type { ClientRenderer, JsonObject, MountContext } from "@assemblejs/core/client";
import { createComponent, sharedConfig } from "solid-js";
import type { Component } from "solid-js";
import { hydrate as hydrateInto } from "solid-js/web";
import type { AssemblyProps } from "../props/assembly-props.js";
import { EventsContext } from "./events-context.js";

/**
 * Turns a Solid component into the browser half of a renderer: it adopts the markup the server
 * sent by its hydration keys, in the envelope or the assembly's own shadow root, and the handle
 * disposes everything it created.
 *
 * Solid keeps its hydration state on `globalThis._$HY`, which its own page bootstrap creates with
 * an inline script the page's policy refuses, and marks hydration done (there, and on its shared
 * configuration) after the first hydration or the first delegated event, after which it would
 * re-render rather than adopt. Each assembly mounts on its own and at its own time, so each gets
 * a fresh state of its own.
 */
export function hydrate(component: Component<AssemblyProps>): ClientRenderer {
  return {
    mount(element: Element | ShadowRoot, data: JsonObject, context: MountContext) {
      (globalThis as { _$HY?: unknown })._$HY = {
        events: [],
        completed: new WeakSet(),
        r: {},
        fe: () => undefined,
        done: false,
      };
      sharedConfig.done = false;
      const dispose = hydrateInto(
        () =>
          createComponent(EventsContext.Provider, {
            value: context.events,
            get children() {
              return createComponent(component, { data, children: {} });
            },
          }),
        element,
      );
      return { unmount: () => dispose() };
    },
  };
}

// packages/renderer-react/src/client/hydrate.ts
// Copyright Ayers Electronics Inc. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
import type { ClientRenderer, JsonObject, MountContext } from "@assemblejs/core/client";
import { createElement } from "react";
import { hydrateRoot } from "react-dom/client";
import type { AssemblyProps } from "../props/assembly-props.js";
import { EventsContext } from "./events-context.js";

/**
 * Turns a React component into the browser half of a renderer.
 *
 * `mount` receives the element already resolved and returns a handle the runtime calls. An
 * adapter that looked its own root up would no-op silently when the lookup missed, which is the
 * predecessor's defect: nothing appeared and nothing said why.
 */
export function hydrate(component: (props: AssemblyProps) => unknown): ClientRenderer {
  return {
    mount(element: Element | ShadowRoot, data: JsonObject, context: MountContext) {
      const root = hydrateRoot(
        // React accepts a shadow root at run time (any element, document or fragment container);
        // its type names only the first two.
        element as Element,
        createElement(
          EventsContext.Provider,
          { value: context.events },
          createElement(component as never, { data, children: {} }),
        ),
      );
      return { unmount: () => root.unmount() };
    },
  };
}
