// examples/frameworks/src/assemblies/preact-shell/preact-shell.preact.tsx
// Copyright Ayers Electronics Inc. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
import { Slot } from "@assemblejs/renderer-preact/client";
import { useState } from "preact/hooks";

// A Preact assembly that places a Vue one.
export default function PreactShell() {
  const [count, setCount] = useState(0);
  return (
    <section>
      <button type="button" id="preact-shell-bump" onClick={() => setCount(count + 1)}>
        preact shell {count}
      </button>
      <Slot name="vue-counter" />
    </section>
  );
}

// examples/frameworks/src/assemblies/solid-shell/solid-shell.solid.tsx
// Copyright Ayers Electronics Inc. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
import { Slot } from "@assemblejs/renderer-solid/client";
import { createSignal } from "solid-js";

// A Solid assembly that places a Lit one.
export default function SolidShell() {
  const [count, setCount] = createSignal(0);
  return (
    <section>
      <button type="button" id="solid-shell-bump" onClick={() => setCount(count() + 1)}>
        solid shell {count()}
      </button>
      <Slot name="lit-counter" />
    </section>
  );
}
