// examples/frameworks/src/assemblies/solid-shell/solid-shell.solid.tsx
// Copyright Ayers Electronics Inc. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
import { Slot } from "@assemblejs/renderer-solid/client";
import { createSignal } from "solid-js";

// A Solid assembly that places a Lit one.
export default function SolidShell() {
  const [count, setCount] = createSignal(0);
  return (
    <section>
      <button type="button" id="solid-shell-bump" onClick={() => setCount(count() + 1)}>
        solid shell {count()}
      </button>
      <Slot name="lit-counter" />
    </section>
  );
}

// examples/frameworks/src/assemblies/react-shell/react-shell.react.tsx
// Copyright Ayers Electronics Inc. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
import { Slot } from "@assemblejs/renderer-react/client";
import { useState } from "react";

// A React assembly that places a Svelte one. The slot writes the directive, the server puts the
// counter where it stood, and React leaves it alone when this assembly renders again.
export default function ReactShell() {
  const [count, setCount] = useState(0);
  return (
    <section>
      <button type="button" id="react-shell-bump" onClick={() => setCount(count + 1)}>
        react shell {count}
      </button>
      <Slot name="svelte-counter" />
    </section>
  );
}
