// examples/shadow/src/assemblies/solid-box/solid-box.solid.tsx
// Copyright Ayers Electronics Inc. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
import { createSignal } from "solid-js";

export const shadow = true;

export default function SolidBox() {
  const [count, setCount] = createSignal(0);
  return (
    <button type="button" class="bump" id="solid-bump" onClick={() => setCount(count() + 1)}>
      solid {count()}
    </button>
  );
}

// examples/shadow/src/assemblies/preact-box/preact-box.preact.tsx
// Copyright Ayers Electronics Inc. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
import { useState } from "preact/hooks";

export const shadow = true;

export default function PreactBox() {
  const [count, setCount] = useState(0);
  return (
    <button type="button" class="bump" id="preact-bump" onClick={() => setCount(count + 1)}>
      preact {count}
    </button>
  );
}
